import com.newspace.discounts.OrderRequest;
dialect  "mvel"

rule "Discount for CARD payment above 10000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 10000 );
    then
        orderObject.setDiscount(15);
end;

rule "Discount for CARD payment below 10000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 5000 && totalPrice < 10000 );
    then
        orderObject.setDiscount(5);
end;

rule "Discount for CASH payment above 25000"
    when
        orderObject : OrderRequest( paymentType=="CASH" && totalPrice > 25000 );
    then
        orderObject.setDiscount(30);
end;

// rule "Discount for CHEQUE or APP TRANSFER payment will be 0"
//     when
//         orderObject : OrderRequest( paymentType=="CHEQUE" || paymentType=="APP TRANSFER" );
//     then
//         orderObject.setDiscount(0);
// end;