package com.newspace.discounts;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrderRequest() {
    }




}